<?php 
global $luv_iconset, $luv_svg_iconset;

$luv_iconset = array (
	
	'FontAwesome' => array (
		'fa fa-address-book', 
		'fa fa-address-book-o', 
		'fa fa-address-card', 
		'fa fa-address-card-o', 
		'fa fa-bandcamp', 
		'fa fa-bath', 
		'fa fa-bathtub', 
		'fa fa-drivers-license', 
		'fa fa-drivers-license-o', 
		'fa fa-eercast', 
		'fa fa-envelope-open', 
		'fa fa-envelope-open-o', 
		'fa fa-etsy', 
		'fa fa-free-code-camp', 
		'fa fa-grav', 
		'fa fa-handshake-o', 
		'fa fa-id-badge', 
		'fa fa-id-card', 
		'fa fa-id-card-o', 
		'fa fa-imdb', 
		'fa fa-linode', 
		'fa fa-meetup', 
		'fa fa-microchip', 
		'fa fa-podcast', 
		'fa fa-quora', 
		'fa fa-ravelry', 
		'fa fa-s15', 
		'fa fa-shower', 
		'fa fa-snowflake-o', 
		'fa fa-superpowers', 
		'fa fa-telegram', 
		'fa fa-thermometer', 
		'fa fa-thermometer-0', 
		'fa fa-thermometer-1', 
		'fa fa-thermometer-2', 
		'fa fa-thermometer-3', 
		'fa fa-thermometer-4', 
		'fa fa-thermometer-empty', 
		'fa fa-thermometer-full', 
		'fa fa-thermometer-half', 
		'fa fa-thermometer-quarter', 
		'fa fa-thermometer-three-quarters', 
		'fa fa-times-rectangle', 
		'fa fa-times-rectangle-o', 
		'fa fa-user-circle', 
		'fa fa-user-circle-o', 
		'fa fa-user-o', 
		'fa fa-vcard', 
		'fa fa-vcard-o', 
		'fa fa-window-close', 
		'fa fa-window-close-o', 
		'fa fa-window-maximize', 
		'fa fa-window-minimize', 
		'fa fa-window-restore', 
		'fa fa-wpexplorer', 
		'fa fa-address-book', 
		'fa fa-address-book-o', 
		'fa fa-address-card', 
		'fa fa-address-card-o', 
		'fa fa-adjust', 
		'fa fa-american-sign-language-interpreting', 
		'fa fa-anchor', 
		'fa fa-archive', 
		'fa fa-area-chart', 
		'fa fa-arrows', 
		'fa fa-arrows-h', 
		'fa fa-arrows-v', 
		'fa fa-asl-interpreting', 
		'fa fa-assistive-listening-systems', 
		'fa fa-asterisk', 
		'fa fa-at', 
		'fa fa-audio-description', 
		'fa fa-automobile', 
		'fa fa-balance-scale', 
		'fa fa-ban', 
		'fa fa-bank', 
		'fa fa-bar-chart', 
		'fa fa-bar-chart-o', 
		'fa fa-barcode', 
		'fa fa-bars', 
		'fa fa-bath', 
		'fa fa-bathtub', 
		'fa fa-battery', 
		'fa fa-battery-0', 
		'fa fa-battery-1', 
		'fa fa-battery-2', 
		'fa fa-battery-3', 
		'fa fa-battery-4', 
		'fa fa-battery-empty', 
		'fa fa-battery-full', 
		'fa fa-battery-half', 
		'fa fa-battery-quarter', 
		'fa fa-battery-three-quarters', 
		'fa fa-bed', 
		'fa fa-beer', 
		'fa fa-bell', 
		'fa fa-bell-o', 
		'fa fa-bell-slash', 
		'fa fa-bell-slash-o', 
		'fa fa-bicycle', 
		'fa fa-binoculars', 
		'fa fa-birthday-cake', 
		'fa fa-blind', 
		'fa fa-bluetooth', 
		'fa fa-bluetooth-b', 
		'fa fa-bolt', 
		'fa fa-bomb', 
		'fa fa-book', 
		'fa fa-bookmark', 
		'fa fa-bookmark-o', 
		'fa fa-braille', 
		'fa fa-briefcase', 
		'fa fa-bug', 
		'fa fa-building', 
		'fa fa-building-o', 
		'fa fa-bullhorn', 
		'fa fa-bullseye', 
		'fa fa-bus', 
		'fa fa-cab', 
		'fa fa-calculator', 
		'fa fa-calendar', 
		'fa fa-calendar-check-o', 
		'fa fa-calendar-minus-o', 
		'fa fa-calendar-o', 
		'fa fa-calendar-plus-o', 
		'fa fa-calendar-times-o', 
		'fa fa-camera', 
		'fa fa-camera-retro', 
		'fa fa-car', 
		'fa fa-caret-square-o-down', 
		'fa fa-caret-square-o-left', 
		'fa fa-caret-square-o-right', 
		'fa fa-caret-square-o-up', 
		'fa fa-cart-arrow-down', 
		'fa fa-cart-plus', 
		'fa fa-cc', 
		'fa fa-certificate', 
		'fa fa-check', 
		'fa fa-check-circle', 
		'fa fa-check-circle-o', 
		'fa fa-check-square', 
		'fa fa-check-square-o', 
		'fa fa-child', 
		'fa fa-circle', 
		'fa fa-circle-o', 
		'fa fa-circle-o-notch', 
		'fa fa-circle-thin', 
		'fa fa-clock-o', 
		'fa fa-clone', 
		'fa fa-close', 
		'fa fa-cloud', 
		'fa fa-cloud-download', 
		'fa fa-cloud-upload', 
		'fa fa-code', 
		'fa fa-code-fork', 
		'fa fa-coffee', 
		'fa fa-cog', 
		'fa fa-cogs', 
		'fa fa-comment', 
		'fa fa-comment-o', 
		'fa fa-commenting', 
		'fa fa-commenting-o', 
		'fa fa-comments', 
		'fa fa-comments-o', 
		'fa fa-compass', 
		'fa fa-copyright', 
		'fa fa-creative-commons', 
		'fa fa-credit-card', 
		'fa fa-credit-card-alt', 
		'fa fa-crop', 
		'fa fa-crosshairs', 
		'fa fa-cube', 
		'fa fa-cubes', 
		'fa fa-cutlery', 
		'fa fa-dashboard', 
		'fa fa-database', 
		'fa fa-deaf', 
		'fa fa-deafness', 
		'fa fa-desktop', 
		'fa fa-diamond', 
		'fa fa-dot-circle-o', 
		'fa fa-download', 
		'fa fa-drivers-license', 
		'fa fa-drivers-license-o', 
		'fa fa-edit', 
		'fa fa-ellipsis-h', 
		'fa fa-ellipsis-v', 
		'fa fa-envelope', 
		'fa fa-envelope-o', 
		'fa fa-envelope-open', 
		'fa fa-envelope-open-o', 
		'fa fa-envelope-square', 
		'fa fa-eraser', 
		'fa fa-exchange', 
		'fa fa-exclamation', 
		'fa fa-exclamation-circle', 
		'fa fa-exclamation-triangle', 
		'fa fa-external-link', 
		'fa fa-external-link-square', 
		'fa fa-eye', 
		'fa fa-eye-slash', 
		'fa fa-eyedropper', 
		'fa fa-fax', 
		'fa fa-feed', 
		'fa fa-female', 
		'fa fa-fighter-jet', 
		'fa fa-file-archive-o', 
		'fa fa-file-audio-o', 
		'fa fa-file-code-o', 
		'fa fa-file-excel-o', 
		'fa fa-file-image-o', 
		'fa fa-file-movie-o', 
		'fa fa-file-pdf-o', 
		'fa fa-file-photo-o', 
		'fa fa-file-picture-o', 
		'fa fa-file-powerpoint-o', 
		'fa fa-file-sound-o', 
		'fa fa-file-video-o', 
		'fa fa-file-word-o', 
		'fa fa-file-zip-o', 
		'fa fa-film', 
		'fa fa-filter', 
		'fa fa-fire', 
		'fa fa-fire-extinguisher', 
		'fa fa-flag', 
		'fa fa-flag-checkered', 
		'fa fa-flag-o', 
		'fa fa-flash', 
		'fa fa-flask', 
		'fa fa-folder', 
		'fa fa-folder-o', 
		'fa fa-folder-open', 
		'fa fa-folder-open-o', 
		'fa fa-frown-o', 
		'fa fa-futbol-o', 
		'fa fa-gamepad', 
		'fa fa-gavel', 
		'fa fa-gear', 
		'fa fa-gears', 
		'fa fa-gift', 
		'fa fa-glass', 
		'fa fa-globe', 
		'fa fa-graduation-cap', 
		'fa fa-group', 
		'fa fa-hand-grab-o', 
		'fa fa-hand-lizard-o', 
		'fa fa-hand-paper-o', 
		'fa fa-hand-peace-o', 
		'fa fa-hand-pointer-o', 
		'fa fa-hand-rock-o', 
		'fa fa-hand-scissors-o', 
		'fa fa-hand-spock-o', 
		'fa fa-hand-stop-o', 
		'fa fa-handshake-o', 
		'fa fa-hard-of-hearing', 
		'fa fa-hashtag', 
		'fa fa-hdd-o', 
		'fa fa-headphones', 
		'fa fa-heart', 
		'fa fa-heart-o', 
		'fa fa-heartbeat', 
		'fa fa-history', 
		'fa fa-home', 
		'fa fa-hotel', 
		'fa fa-hourglass', 
		'fa fa-hourglass-1', 
		'fa fa-hourglass-2', 
		'fa fa-hourglass-3', 
		'fa fa-hourglass-end', 
		'fa fa-hourglass-half', 
		'fa fa-hourglass-o', 
		'fa fa-hourglass-start', 
		'fa fa-i-cursor', 
		'fa fa-id-badge', 
		'fa fa-id-card', 
		'fa fa-id-card-o', 
		'fa fa-image', 
		'fa fa-inbox', 
		'fa fa-industry', 
		'fa fa-info', 
		'fa fa-info-circle', 
		'fa fa-institution', 
		'fa fa-key', 
		'fa fa-keyboard-o', 
		'fa fa-language', 
		'fa fa-laptop', 
		'fa fa-leaf', 
		'fa fa-legal', 
		'fa fa-lemon-o', 
		'fa fa-level-down', 
		'fa fa-level-up', 
		'fa fa-life-bouy', 
		'fa fa-life-buoy', 
		'fa fa-life-ring', 
		'fa fa-life-saver', 
		'fa fa-lightbulb-o', 
		'fa fa-line-chart', 
		'fa fa-location-arrow', 
		'fa fa-lock', 
		'fa fa-low-vision', 
		'fa fa-magic', 
		'fa fa-magnet', 
		'fa fa-mail-forward', 
		'fa fa-mail-reply', 
		'fa fa-mail-reply-all', 
		'fa fa-male', 
		'fa fa-map', 
		'fa fa-map-marker', 
		'fa fa-map-o', 
		'fa fa-map-pin', 
		'fa fa-map-signs', 
		'fa fa-meh-o', 
		'fa fa-microchip', 
		'fa fa-microphone', 
		'fa fa-microphone-slash', 
		'fa fa-minus', 
		'fa fa-minus-circle', 
		'fa fa-minus-square', 
		'fa fa-minus-square-o', 
		'fa fa-mobile', 
		'fa fa-mobile-phone', 
		'fa fa-money', 
		'fa fa-moon-o', 
		'fa fa-mortar-board', 
		'fa fa-motorcycle', 
		'fa fa-mouse-pointer', 
		'fa fa-music', 
		'fa fa-navicon', 
		'fa fa-newspaper-o', 
		'fa fa-object-group', 
		'fa fa-object-ungroup', 
		'fa fa-paint-brush', 
		'fa fa-paper-plane', 
		'fa fa-paper-plane-o', 
		'fa fa-paw', 
		'fa fa-pencil', 
		'fa fa-pencil-square', 
		'fa fa-pencil-square-o', 
		'fa fa-percent', 
		'fa fa-phone', 
		'fa fa-phone-square', 
		'fa fa-photo', 
		'fa fa-picture-o', 
		'fa fa-pie-chart', 
		'fa fa-plane', 
		'fa fa-plug', 
		'fa fa-plus', 
		'fa fa-plus-circle', 
		'fa fa-plus-square', 
		'fa fa-plus-square-o', 
		'fa fa-podcast', 
		'fa fa-power-off', 
		'fa fa-print', 
		'fa fa-puzzle-piece', 
		'fa fa-qrcode', 
		'fa fa-question', 
		'fa fa-question-circle', 
		'fa fa-question-circle-o', 
		'fa fa-quote-left', 
		'fa fa-quote-right', 
		'fa fa-random', 
		'fa fa-recycle', 
		'fa fa-refresh', 
		'fa fa-registered', 
		'fa fa-remove', 
		'fa fa-reorder', 
		'fa fa-reply', 
		'fa fa-reply-all', 
		'fa fa-retweet', 
		'fa fa-road', 
		'fa fa-rocket', 
		'fa fa-rss', 
		'fa fa-rss-square', 
		'fa fa-s15', 
		'fa fa-search', 
		'fa fa-search-minus', 
		'fa fa-search-plus', 
		'fa fa-send', 
		'fa fa-send-o', 
		'fa fa-server', 
		'fa fa-share', 
		'fa fa-share-alt', 
		'fa fa-share-alt-square', 
		'fa fa-share-square', 
		'fa fa-share-square-o', 
		'fa fa-shield', 
		'fa fa-ship', 
		'fa fa-shopping-bag', 
		'fa fa-shopping-basket', 
		'fa fa-shopping-cart', 
		'fa fa-shower', 
		'fa fa-sign-in', 
		'fa fa-sign-language', 
		'fa fa-sign-out', 
		'fa fa-signal', 
		'fa fa-signing', 
		'fa fa-sitemap', 
		'fa fa-sliders', 
		'fa fa-smile-o', 
		'fa fa-snowflake-o', 
		'fa fa-soccer-ball-o', 
		'fa fa-sort', 
		'fa fa-sort-alpha-asc', 
		'fa fa-sort-alpha-desc', 
		'fa fa-sort-amount-asc', 
		'fa fa-sort-amount-desc', 
		'fa fa-sort-asc', 
		'fa fa-sort-desc', 
		'fa fa-sort-down', 
		'fa fa-sort-numeric-asc', 
		'fa fa-sort-numeric-desc', 
		'fa fa-sort-up', 
		'fa fa-space-shuttle', 
		'fa fa-spinner', 
		'fa fa-spoon', 
		'fa fa-square', 
		'fa fa-square-o', 
		'fa fa-star', 
		'fa fa-star-half', 
		'fa fa-star-half-empty', 
		'fa fa-star-half-full', 
		'fa fa-star-half-o', 
		'fa fa-star-o', 
		'fa fa-sticky-note', 
		'fa fa-sticky-note-o', 
		'fa fa-street-view', 
		'fa fa-suitcase', 
		'fa fa-sun-o', 
		'fa fa-support', 
		'fa fa-tablet', 
		'fa fa-tachometer', 
		'fa fa-tag', 
		'fa fa-tags', 
		'fa fa-tasks', 
		'fa fa-taxi', 
		'fa fa-television', 
		'fa fa-terminal', 
		'fa fa-thermometer', 
		'fa fa-thermometer-0', 
		'fa fa-thermometer-1', 
		'fa fa-thermometer-2', 
		'fa fa-thermometer-3', 
		'fa fa-thermometer-4', 
		'fa fa-thermometer-empty', 
		'fa fa-thermometer-full', 
		'fa fa-thermometer-half', 
		'fa fa-thermometer-quarter', 
		'fa fa-thermometer-three-quarters', 
		'fa fa-thumb-tack', 
		'fa fa-thumbs-down', 
		'fa fa-thumbs-o-down', 
		'fa fa-thumbs-o-up', 
		'fa fa-thumbs-up', 
		'fa fa-ticket', 
		'fa fa-times', 
		'fa fa-times-circle', 
		'fa fa-times-circle-o', 
		'fa fa-times-rectangle', 
		'fa fa-times-rectangle-o', 
		'fa fa-tint', 
		'fa fa-toggle-down', 
		'fa fa-toggle-left', 
		'fa fa-toggle-off', 
		'fa fa-toggle-on', 
		'fa fa-toggle-right', 
		'fa fa-toggle-up', 
		'fa fa-trademark', 
		'fa fa-trash', 
		'fa fa-trash-o', 
		'fa fa-tree', 
		'fa fa-trophy', 
		'fa fa-truck', 
		'fa fa-tty', 
		'fa fa-tv', 
		'fa fa-umbrella', 
		'fa fa-universal-access', 
		'fa fa-university', 
		'fa fa-unlock', 
		'fa fa-unlock-alt', 
		'fa fa-unsorted', 
		'fa fa-upload', 
		'fa fa-user', 
		'fa fa-user-circle', 
		'fa fa-user-circle-o', 
		'fa fa-user-o', 
		'fa fa-user-plus', 
		'fa fa-user-secret', 
		'fa fa-user-times', 
		'fa fa-users', 
		'fa fa-vcard', 
		'fa fa-vcard-o', 
		'fa fa-video-camera', 
		'fa fa-volume-control-phone', 
		'fa fa-volume-down', 
		'fa fa-volume-off', 
		'fa fa-volume-up', 
		'fa fa-warning', 
		'fa fa-wheelchair', 
		'fa fa-wheelchair-alt', 
		'fa fa-wifi', 
		'fa fa-window-close', 
		'fa fa-window-close-o', 
		'fa fa-window-maximize', 
		'fa fa-window-minimize', 
		'fa fa-window-restore', 
		'fa fa-wrench', 
		'fa fa-american-sign-language-interpreting', 
		'fa fa-asl-interpreting', 
		'fa fa-assistive-listening-systems', 
		'fa fa-audio-description', 
		'fa fa-blind', 
		'fa fa-braille', 
		'fa fa-cc', 
		'fa fa-deaf', 
		'fa fa-deafness', 
		'fa fa-hard-of-hearing', 
		'fa fa-low-vision', 
		'fa fa-question-circle-o', 
		'fa fa-sign-language', 
		'fa fa-signing', 
		'fa fa-tty', 
		'fa fa-universal-access', 
		'fa fa-volume-control-phone', 
		'fa fa-wheelchair', 
		'fa fa-wheelchair-alt', 
		'fa fa-hand-grab-o', 
		'fa fa-hand-lizard-o', 
		'fa fa-hand-o-down', 
		'fa fa-hand-o-left', 
		'fa fa-hand-o-right', 
		'fa fa-hand-o-up', 
		'fa fa-hand-paper-o', 
		'fa fa-hand-peace-o', 
		'fa fa-hand-pointer-o', 
		'fa fa-hand-rock-o', 
		'fa fa-hand-scissors-o', 
		'fa fa-hand-spock-o', 
		'fa fa-hand-stop-o', 
		'fa fa-thumbs-down', 
		'fa fa-thumbs-o-down', 
		'fa fa-thumbs-o-up', 
		'fa fa-thumbs-up', 
		'fa fa-ambulance', 
		'fa fa-automobile', 
		'fa fa-bicycle', 
		'fa fa-bus', 
		'fa fa-cab', 
		'fa fa-car', 
		'fa fa-fighter-jet', 
		'fa fa-motorcycle', 
		'fa fa-plane', 
		'fa fa-rocket', 
		'fa fa-ship', 
		'fa fa-space-shuttle', 
		'fa fa-subway', 
		'fa fa-taxi', 
		'fa fa-train', 
		'fa fa-truck', 
		'fa fa-wheelchair', 
		'fa fa-wheelchair-alt', 
		'fa fa-genderless', 
		'fa fa-intersex', 
		'fa fa-mars', 
		'fa fa-mars-double', 
		'fa fa-mars-stroke', 
		'fa fa-mars-stroke-h', 
		'fa fa-mars-stroke-v', 
		'fa fa-mercury', 
		'fa fa-neuter', 
		'fa fa-transgender', 
		'fa fa-transgender-alt', 
		'fa fa-venus', 
		'fa fa-venus-double', 
		'fa fa-venus-mars', 
		'fa fa-file', 
		'fa fa-file-archive-o', 
		'fa fa-file-audio-o', 
		'fa fa-file-code-o', 
		'fa fa-file-excel-o', 
		'fa fa-file-image-o', 
		'fa fa-file-movie-o', 
		'fa fa-file-o', 
		'fa fa-file-pdf-o', 
		'fa fa-file-photo-o', 
		'fa fa-file-picture-o', 
		'fa fa-file-powerpoint-o', 
		'fa fa-file-sound-o', 
		'fa fa-file-text', 
		'fa fa-file-text-o', 
		'fa fa-file-video-o', 
		'fa fa-file-word-o', 
		'fa fa-file-zip-o', 
		'fa fa-info-circle', 
		'fa fa-circle-o-notch', 
		'fa fa-cog', 
		'fa fa-gear', 
		'fa fa-refresh', 
		'fa fa-spinner', 
		'fa fa-check-square', 
		'fa fa-check-square-o', 
		'fa fa-circle', 
		'fa fa-circle-o', 
		'fa fa-dot-circle-o', 
		'fa fa-minus-square', 
		'fa fa-minus-square-o', 
		'fa fa-plus-square', 
		'fa fa-plus-square-o', 
		'fa fa-square', 
		'fa fa-square-o', 
		'fa fa-cc-amex', 
		'fa fa-cc-diners-club', 
		'fa fa-cc-discover', 
		'fa fa-cc-jcb', 
		'fa fa-cc-mastercard', 
		'fa fa-cc-paypal', 
		'fa fa-cc-stripe', 
		'fa fa-cc-visa', 
		'fa fa-credit-card', 
		'fa fa-credit-card-alt', 
		'fa fa-google-wallet', 
		'fa fa-paypal', 
		'fa fa-area-chart', 
		'fa fa-bar-chart', 
		'fa fa-bar-chart-o', 
		'fa fa-line-chart', 
		'fa fa-pie-chart', 
		'fa fa-bitcoin', 
		'fa fa-btc', 
		'fa fa-cny', 
		'fa fa-dollar', 
		'fa fa-eur', 
		'fa fa-euro', 
		'fa fa-gbp', 
		'fa fa-gg', 
		'fa fa-gg-circle', 
		'fa fa-ils', 
		'fa fa-inr', 
		'fa fa-jpy', 
		'fa fa-krw', 
		'fa fa-money', 
		'fa fa-rmb', 
		'fa fa-rouble', 
		'fa fa-rub', 
		'fa fa-ruble', 
		'fa fa-rupee', 
		'fa fa-shekel', 
		'fa fa-sheqel', 
		'fa fa-try', 
		'fa fa-turkish-lira', 
		'fa fa-usd', 
		'fa fa-won', 
		'fa fa-yen', 
		'fa fa-align-center', 
		'fa fa-align-justify', 
		'fa fa-align-left', 
		'fa fa-align-right', 
		'fa fa-bold', 
		'fa fa-chain', 
		'fa fa-chain-broken', 
		'fa fa-clipboard', 
		'fa fa-columns', 
		'fa fa-copy', 
		'fa fa-cut', 
		'fa fa-dedent', 
		'fa fa-eraser', 
		'fa fa-file', 
		'fa fa-file-o', 
		'fa fa-file-text', 
		'fa fa-file-text-o', 
		'fa fa-files-o', 
		'fa fa-floppy-o', 
		'fa fa-font', 
		'fa fa-header', 
		'fa fa-indent', 
		'fa fa-italic', 
		'fa fa-link', 
		'fa fa-list', 
		'fa fa-list-alt', 
		'fa fa-list-ol', 
		'fa fa-list-ul', 
		'fa fa-outdent', 
		'fa fa-paperclip', 
		'fa fa-paragraph', 
		'fa fa-paste', 
		'fa fa-repeat', 
		'fa fa-rotate-left', 
		'fa fa-rotate-right', 
		'fa fa-save', 
		'fa fa-scissors', 
		'fa fa-strikethrough', 
		'fa fa-subscript', 
		'fa fa-superscript', 
		'fa fa-table', 
		'fa fa-text-height', 
		'fa fa-text-width', 
		'fa fa-th', 
		'fa fa-th-large', 
		'fa fa-th-list', 
		'fa fa-underline', 
		'fa fa-undo', 
		'fa fa-unlink', 
		'fa fa-angle-double-down', 
		'fa fa-angle-double-left', 
		'fa fa-angle-double-right', 
		'fa fa-angle-double-up', 
		'fa fa-angle-down', 
		'fa fa-angle-left', 
		'fa fa-angle-right', 
		'fa fa-angle-up', 
		'fa fa-arrow-circle-down', 
		'fa fa-arrow-circle-left', 
		'fa fa-arrow-circle-o-down', 
		'fa fa-arrow-circle-o-left', 
		'fa fa-arrow-circle-o-right', 
		'fa fa-arrow-circle-o-up', 
		'fa fa-arrow-circle-right', 
		'fa fa-arrow-circle-up', 
		'fa fa-arrow-down', 
		'fa fa-arrow-left', 
		'fa fa-arrow-right', 
		'fa fa-arrow-up', 
		'fa fa-arrows', 
		'fa fa-arrows-alt', 
		'fa fa-arrows-h', 
		'fa fa-arrows-v', 
		'fa fa-caret-down', 
		'fa fa-caret-left', 
		'fa fa-caret-right', 
		'fa fa-caret-square-o-down', 
		'fa fa-caret-square-o-left', 
		'fa fa-caret-square-o-right', 
		'fa fa-caret-square-o-up', 
		'fa fa-caret-up', 
		'fa fa-chevron-circle-down', 
		'fa fa-chevron-circle-left', 
		'fa fa-chevron-circle-right', 
		'fa fa-chevron-circle-up', 
		'fa fa-chevron-down', 
		'fa fa-chevron-left', 
		'fa fa-chevron-right', 
		'fa fa-chevron-up', 
		'fa fa-exchange', 
		'fa fa-hand-o-down', 
		'fa fa-hand-o-left', 
		'fa fa-hand-o-right', 
		'fa fa-hand-o-up', 
		'fa fa-long-arrow-down', 
		'fa fa-long-arrow-left', 
		'fa fa-long-arrow-right', 
		'fa fa-long-arrow-up', 
		'fa fa-toggle-down', 
		'fa fa-toggle-left', 
		'fa fa-toggle-right', 
		'fa fa-toggle-up', 
		'fa fa-arrows-alt', 
		'fa fa-backward', 
		'fa fa-compress', 
		'fa fa-eject', 
		'fa fa-expand', 
		'fa fa-fast-backward', 
		'fa fa-fast-forward', 
		'fa fa-forward', 
		'fa fa-pause', 
		'fa fa-pause-circle', 
		'fa fa-pause-circle-o', 
		'fa fa-play', 
		'fa fa-play-circle', 
		'fa fa-play-circle-o', 
		'fa fa-random', 
		'fa fa-step-backward', 
		'fa fa-step-forward', 
		'fa fa-stop', 
		'fa fa-stop-circle', 
		'fa fa-stop-circle-o', 
		'fa fa-youtube-play', 
		'fa fa-500px', 
		'fa fa-adn', 
		'fa fa-amazon', 
		'fa fa-android', 
		'fa fa-angellist', 
		'fa fa-apple', 
		'fa fa-bandcamp', 
		'fa fa-behance', 
		'fa fa-behance-square', 
		'fa fa-bitbucket', 
		'fa fa-bitbucket-square', 
		'fa fa-bitcoin', 
		'fa fa-black-tie', 
		'fa fa-bluetooth', 
		'fa fa-bluetooth-b', 
		'fa fa-btc', 
		'fa fa-buysellads', 
		'fa fa-cc-amex', 
		'fa fa-cc-diners-club', 
		'fa fa-cc-discover', 
		'fa fa-cc-jcb', 
		'fa fa-cc-mastercard', 
		'fa fa-cc-paypal', 
		'fa fa-cc-stripe', 
		'fa fa-cc-visa', 
		'fa fa-chrome', 
		'fa fa-codepen', 
		'fa fa-codiepie', 
		'fa fa-connectdevelop', 
		'fa fa-contao', 
		'fa fa-css3', 
		'fa fa-dashcube', 
		'fa fa-delicious', 
		'fa fa-deviantart', 
		'fa fa-digg', 
		'fa fa-dribbble', 
		'fa fa-dropbox', 
		'fa fa-drupal', 
		'fa fa-edge', 
		'fa fa-eercast', 
		'fa fa-empire', 
		'fa fa-envira', 
		'fa fa-etsy', 
		'fa fa-expeditedssl', 
		'fa fa-fa', 
		'fa fa-facebook', 
		'fa fa-facebook-f', 
		'fa fa-facebook-official', 
		'fa fa-facebook-square', 
		'fa fa-firefox', 
		'fa fa-first-order', 
		'fa fa-flickr', 
		'fa fa-font-awesome', 
		'fa fa-fonticons', 
		'fa fa-fort-awesome', 
		'fa fa-forumbee', 
		'fa fa-foursquare', 
		'fa fa-free-code-camp', 
		'fa fa-ge', 
		'fa fa-get-pocket', 
		'fa fa-gg', 
		'fa fa-gg-circle', 
		'fa fa-git', 
		'fa fa-git-square', 
		'fa fa-github', 
		'fa fa-github-alt', 
		'fa fa-github-square', 
		'fa fa-gitlab', 
		'fa fa-gittip', 
		'fa fa-glide', 
		'fa fa-glide-g', 
		'fa fa-google', 
		'fa fa-google-plus', 
		'fa fa-google-plus-circle', 
		'fa fa-google-plus-official', 
		'fa fa-google-plus-square', 
		'fa fa-google-wallet', 
		'fa fa-gratipay', 
		'fa fa-grav', 
		'fa fa-hacker-news', 
		'fa fa-houzz', 
		'fa fa-html5', 
		'fa fa-imdb', 
		'fa fa-instagram', 
		'fa fa-internet-explorer', 
		'fa fa-ioxhost', 
		'fa fa-joomla', 
		'fa fa-jsfiddle', 
		'fa fa-lastfm', 
		'fa fa-lastfm-square', 
		'fa fa-leanpub', 
		'fa fa-linkedin', 
		'fa fa-linkedin-square', 
		'fa fa-linode', 
		'fa fa-linux', 
		'fa fa-maxcdn', 
		'fa fa-meanpath', 
		'fa fa-medium', 
		'fa fa-meetup', 
		'fa fa-mixcloud', 
		'fa fa-modx', 
		'fa fa-odnoklassniki', 
		'fa fa-odnoklassniki-square', 
		'fa fa-opencart', 
		'fa fa-openid', 
		'fa fa-opera', 
		'fa fa-optin-monster', 
		'fa fa-pagelines', 
		'fa fa-paypal', 
		'fa fa-pied-piper', 
		'fa fa-pied-piper-alt', 
		'fa fa-pied-piper-pp', 
		'fa fa-pinterest', 
		'fa fa-pinterest-p', 
		'fa fa-pinterest-square', 
		'fa fa-product-hunt', 
		'fa fa-qq', 
		'fa fa-quora', 
		'fa fa-ra', 
		'fa fa-ravelry', 
		'fa fa-rebel', 
		'fa fa-reddit', 
		'fa fa-reddit-alien', 
		'fa fa-reddit-square', 
		'fa fa-renren', 
		'fa fa-resistance', 
		'fa fa-safari', 
		'fa fa-scribd', 
		'fa fa-sellsy', 
		'fa fa-share-alt', 
		'fa fa-share-alt-square', 
		'fa fa-shirtsinbulk', 
		'fa fa-simplybuilt', 
		'fa fa-skyatlas', 
		'fa fa-skype', 
		'fa fa-slack', 
		'fa fa-slideshare', 
		'fa fa-snapchat', 
		'fa fa-snapchat-ghost', 
		'fa fa-snapchat-square', 
		'fa fa-soundcloud', 
		'fa fa-spotify', 
		'fa fa-stack-exchange', 
		'fa fa-stack-overflow', 
		'fa fa-steam', 
		'fa fa-steam-square', 
		'fa fa-stumbleupon', 
		'fa fa-stumbleupon-circle', 
		'fa fa-superpowers', 
		'fa fa-telegram', 
		'fa fa-tencent-weibo', 
		'fa fa-themeisle', 
		'fa fa-trello', 
		'fa fa-tripadvisor', 
		'fa fa-tumblr', 
		'fa fa-tumblr-square', 
		'fa fa-twitch', 
		'fa fa-twitter', 
		'fa fa-twitter-square', 
		'fa fa-usb', 
		'fa fa-viacoin', 
		'fa fa-viadeo', 
		'fa fa-viadeo-square', 
		'fa fa-vimeo', 
		'fa fa-vimeo-square', 
		'fa fa-vine', 
		'fa fa-vk', 
		'fa fa-wechat', 
		'fa fa-weibo', 
		'fa fa-weixin', 
		'fa fa-whatsapp', 
		'fa fa-wikipedia-w', 
		'fa fa-windows', 
		'fa fa-wordpress', 
		'fa fa-wpbeginner', 
		'fa fa-wpexplorer', 
		'fa fa-wpforms', 
		'fa fa-xing', 
		'fa fa-xing-square', 
		'fa fa-y-combinator', 
		'fa fa-y-combinator-square', 
		'fa fa-yahoo', 
		'fa fa-yc', 
		'fa fa-yc-square', 
		'fa fa-yelp', 
		'fa fa-yoast', 
		'fa fa-youtube', 
		'fa fa-youtube-play', 
		'fa fa-youtube-square', 
		'fa fa-warning', 
		'fa fa-ambulance', 
		'fa fa-h-square', 
		'fa fa-heart', 
		'fa fa-heart-o', 
		'fa fa-heartbeat', 
		'fa fa-hospital-o', 
		'fa fa-medkit', 
		'fa fa-plus-square', 
		'fa fa-stethoscope', 
		'fa fa-user-md', 
		'fa fa-wheelchair', 
		'fa fa-wheelchair-alt',
	),
	
	'LineaIcons' => array (
		'linea-icon-basic-accelerator',
		'linea-icon-basic-alarm',
		'linea-icon-basic-anchor',
		'linea-icon-basic-anticlockwise',
		'linea-icon-basic-archive',
		'linea-icon-basic-archive-full',
		'linea-icon-basic-ban',
		'linea-icon-basic-battery-charge',
		'linea-icon-basic-battery-empty',
		'linea-icon-basic-battery-full',
		'linea-icon-basic-battery-half',
		'linea-icon-basic-bolt',
		'linea-icon-basic-book',
		'linea-icon-basic-book-pen',
		'linea-icon-basic-book-pencil',
		'linea-icon-basic-bookmark',
		'linea-icon-basic-calculator',
		'linea-icon-basic-calendar',
		'linea-icon-basic-cards-diamonds',
		'linea-icon-basic-cards-hearts',
		'linea-icon-basic-case',
		'linea-icon-basic-chronometer',
		'linea-icon-basic-clessidre',
		'linea-icon-basic-clock',
		'linea-icon-basic-clockwise',
		'linea-icon-basic-cloud',
		'linea-icon-basic-clubs',
		'linea-icon-basic-compass',
		'linea-icon-basic-cup',
		'linea-icon-basic-diamonds',
		'linea-icon-basic-display',
		'linea-icon-basic-download',
		'linea-icon-basic-exclamation',
		'linea-icon-basic-eye',
		'linea-icon-basic-eye-closed',
		'linea-icon-basic-female',
		'linea-icon-basic-flag1',
		'linea-icon-basic-flag2',
		'linea-icon-basic-floppydisk',
		'linea-icon-basic-folder',
		'linea-icon-basic-folder-multiple',
		'linea-icon-basic-gear',
		'linea-icon-basic-geolocalize-01',
		'linea-icon-basic-geolocalize-05',
		'linea-icon-basic-globe',
		'linea-icon-basic-gunsight',
		'linea-icon-basic-hammer',
		'linea-icon-basic-headset',
		'linea-icon-basic-heart',
		'linea-icon-basic-heart-broken',
		'linea-icon-basic-helm',
		'linea-icon-basic-home',
		'linea-icon-basic-info',
		'linea-icon-basic-ipod',
		'linea-icon-basic-joypad',
		'linea-icon-basic-key',
		'linea-icon-basic-keyboard',
		'linea-icon-basic-laptop',
		'linea-icon-basic-life-buoy',
		'linea-icon-basic-lightbulb',
		'linea-icon-basic-link',
		'linea-icon-basic-lock',
		'linea-icon-basic-lock-open',
		'linea-icon-basic-magic-mouse',
		'linea-icon-basic-magnifier',
		'linea-icon-basic-magnifier-minus',
		'linea-icon-basic-magnifier-plus',
		'linea-icon-basic-mail',
		'linea-icon-basic-mail-multiple',
		'linea-icon-basic-mail-open',
		'linea-icon-basic-mail-open-text',
		'linea-icon-basic-male',
		'linea-icon-basic-map',
		'linea-icon-basic-message',
		'linea-icon-basic-message-multiple',
		'linea-icon-basic-message-txt',
		'linea-icon-basic-mixer2',
		'linea-icon-basic-mouse',
		'linea-icon-basic-notebook',
		'linea-icon-basic-notebook-pen',
		'linea-icon-basic-notebook-pencil',
		'linea-icon-basic-paperplane',
		'linea-icon-basic-pencil-ruler',
		'linea-icon-basic-pencil-ruler-pen',
		'linea-icon-basic-photo',
		'linea-icon-basic-picture',
		'linea-icon-basic-picture-multiple',
		'linea-icon-basic-pin1',
		'linea-icon-basic-pin2',
		'linea-icon-basic-postcard',
		'linea-icon-basic-postcard-multiple',
		'linea-icon-basic-printer',
		'linea-icon-basic-question',
		'linea-icon-basic-rss',
		'linea-icon-basic-server',
		'linea-icon-basic-server2',
		'linea-icon-basic-server-cloud',
		'linea-icon-basic-server-download',
		'linea-icon-basic-server-upload',
		'linea-icon-basic-settings',
		'linea-icon-basic-share',
		'linea-icon-basic-sheet',
		'linea-icon-basic-sheet-multiple',
		'linea-icon-basic-sheet-pen',
		'linea-icon-basic-sheet-pencil',
		'linea-icon-basic-sheet-txt',
		'linea-icon-basic-signs',
		'linea-icon-basic-smartphone',
		'linea-icon-basic-spades',
		'linea-icon-basic-spread',
		'linea-icon-basic-spread-bookmark',
		'linea-icon-basic-spread-text',
		'linea-icon-basic-spread-text-bookmark',
		'linea-icon-basic-star',
		'linea-icon-basic-tablet',
		'linea-icon-basic-target',
		'linea-icon-basic-todo',
		'linea-icon-basic-todo-pen',
		'linea-icon-basic-todo-pencil',
		'linea-icon-basic-todo-txt',
		'linea-icon-basic-todolist-pen',
		'linea-icon-basic-todolist-pencil',
		'linea-icon-basic-trashcan',
		'linea-icon-basic-trashcan-full',
		'linea-icon-basic-trashcan-refresh',
		'linea-icon-basic-trashcan-remove',
		'linea-icon-basic-upload',
		'linea-icon-basic-usb',
		'linea-icon-basic-video',
		'linea-icon-basic-watch',
		'linea-icon-basic-webpage',
		'linea-icon-basic-webpage-img-txt',
		'linea-icon-basic-webpage-multiple',
		'linea-icon-basic-webpage-txt',
		'linea-icon-basic-world',
		'linea-icon-ecommerce-bag',
		'linea-icon-ecommerce-bag-check',
		'linea-icon-ecommerce-bag-cloud',
		'linea-icon-ecommerce-bag-download',
		'linea-icon-ecommerce-bag-minus',
		'linea-icon-ecommerce-bag-plus',
		'linea-icon-ecommerce-bag-refresh',
		'linea-icon-ecommerce-bag-remove',
		'linea-icon-ecommerce-bag-search',
		'linea-icon-ecommerce-bag-upload',
		'linea-icon-ecommerce-banknote',
		'linea-icon-ecommerce-banknotes',
		'linea-icon-ecommerce-basket',
		'linea-icon-ecommerce-basket-check',
		'linea-icon-ecommerce-basket-cloud',
		'linea-icon-ecommerce-basket-download',
		'linea-icon-ecommerce-basket-minus',
		'linea-icon-ecommerce-basket-plus',
		'linea-icon-ecommerce-basket-refresh',
		'linea-icon-ecommerce-basket-remove',
		'linea-icon-ecommerce-basket-search',
		'linea-icon-ecommerce-basket-upload',
		'linea-icon-ecommerce-bath',
		'linea-icon-ecommerce-cart',
		'linea-icon-ecommerce-cart-check',
		'linea-icon-ecommerce-cart-cloud',
		'linea-icon-ecommerce-cart-content',
		'linea-icon-ecommerce-cart-download',
		'linea-icon-ecommerce-cart-minus',
		'linea-icon-ecommerce-cart-plus',
		'linea-icon-ecommerce-cart-refresh',
		'linea-icon-ecommerce-cart-remove',
		'linea-icon-ecommerce-cart-search',
		'linea-icon-ecommerce-cart-upload',
		'linea-icon-ecommerce-cent',
		'linea-icon-ecommerce-colon',
		'linea-icon-ecommerce-creditcard',
		'linea-icon-ecommerce-diamond',
		'linea-icon-ecommerce-dollar',
		'linea-icon-ecommerce-euro',
		'linea-icon-ecommerce-franc',
		'linea-icon-ecommerce-gift',
		'linea-icon-ecommerce-graph1',
		'linea-icon-ecommerce-graph2',
		'linea-icon-ecommerce-graph3',
		'linea-icon-ecommerce-graph-decrease',
		'linea-icon-ecommerce-graph-increase',
		'linea-icon-ecommerce-guarani',
		'linea-icon-ecommerce-kips',
		'linea-icon-ecommerce-lira',
		'linea-icon-ecommerce-megaphone',
		'linea-icon-ecommerce-money',
		'linea-icon-ecommerce-naira',
		'linea-icon-ecommerce-pesos',
		'linea-icon-ecommerce-pound',
		'linea-icon-ecommerce-receipt',
		'linea-icon-ecommerce-receipt-bath',
		'linea-icon-ecommerce-receipt-cent',
		'linea-icon-ecommerce-receipt-dollar',
		'linea-icon-ecommerce-receipt-euro',
		'linea-icon-ecommerce-receipt-franc',
		'linea-icon-ecommerce-receipt-guarani',
		'linea-icon-ecommerce-receipt-kips',
		'linea-icon-ecommerce-receipt-lira',
		'linea-icon-ecommerce-receipt-naira',
		'linea-icon-ecommerce-receipt-pesos',
		'linea-icon-ecommerce-receipt-pound',
		'linea-icon-ecommerce-receipt-rublo',
		'linea-icon-ecommerce-receipt-rupee',
		'linea-icon-ecommerce-receipt-tugrik',
		'linea-icon-ecommerce-receipt-won',
		'linea-icon-ecommerce-receipt-yen',
		'linea-icon-ecommerce-receipt-yen2',
		'linea-icon-ecommerce-recept-colon',
		'linea-icon-ecommerce-rublo',
		'linea-icon-ecommerce-rupee',
		'linea-icon-ecommerce-safe',
		'linea-icon-ecommerce-sale',
		'linea-icon-ecommerce-sales',
		'linea-icon-ecommerce-ticket',
		'linea-icon-ecommerce-tugriks',
		'linea-icon-ecommerce-wallet',
		'linea-icon-ecommerce-won',
		'linea-icon-ecommerce-yen',
		'linea-icon-ecommerce-yen2',
		'linea-icon-music-beginning-button',
		'linea-icon-music-bell',
		'linea-icon-music-cd',
		'linea-icon-music-diapason',
		'linea-icon-music-eject-button',
		'linea-icon-music-end-button',
		'linea-icon-music-fastforward-button',
		'linea-icon-music-headphones',
		'linea-icon-music-ipod',
		'linea-icon-music-loudspeaker',
		'linea-icon-music-microphone',
		'linea-icon-music-microphone-old',
		'linea-icon-music-mixer',
		'linea-icon-music-mute',
		'linea-icon-music-note-multiple',
		'linea-icon-music-note-single',
		'linea-icon-music-pause-button',
		'linea-icon-music-play-button',
		'linea-icon-music-playlist',
		'linea-icon-music-radio-ghettoblaster',
		'linea-icon-music-radio-portable',
		'linea-icon-music-record',
		'linea-icon-music-recordplayer',
		'linea-icon-music-repeat-button',
		'linea-icon-music-rewind-button',
		'linea-icon-music-shuffle-button',
		'linea-icon-music-stop-button',
		'linea-icon-music-tape',
		'linea-icon-music-volume-down',
		'linea-icon-music-volume-up',
		'linea-icon-ecommerce-bag',
		'linea-icon-ecommerce-bag-check',
		'linea-icon-ecommerce-bag-cloud',
		'linea-icon-ecommerce-bag-download',
		'linea-icon-ecommerce-bag-minus',
		'linea-icon-ecommerce-bag-plus',
		'linea-icon-ecommerce-bag-refresh',
		'linea-icon-ecommerce-bag-remove',
		'linea-icon-ecommerce-bag-search',
		'linea-icon-ecommerce-bag-upload',
		'linea-icon-ecommerce-banknote',
		'linea-icon-ecommerce-banknotes',
		'linea-icon-ecommerce-basket',
		'linea-icon-ecommerce-basket-check',
		'linea-icon-ecommerce-basket-cloud',
		'linea-icon-ecommerce-basket-download',
		'linea-icon-ecommerce-basket-minus',
		'linea-icon-ecommerce-basket-plus',
		'linea-icon-ecommerce-basket-refresh',
		'linea-icon-ecommerce-basket-remove',
		'linea-icon-ecommerce-basket-search',
		'linea-icon-ecommerce-basket-upload',
		'linea-icon-ecommerce-bath',
		'linea-icon-ecommerce-cart',
		'linea-icon-ecommerce-cart-check',
		'linea-icon-ecommerce-cart-cloud',
		'linea-icon-ecommerce-cart-content',
		'linea-icon-ecommerce-cart-download',
		'linea-icon-ecommerce-cart-minus',
		'linea-icon-ecommerce-cart-plus',
		'linea-icon-ecommerce-cart-refresh',
		'linea-icon-ecommerce-cart-remove',
		'linea-icon-ecommerce-cart-search',
		'linea-icon-ecommerce-cart-upload',
		'linea-icon-ecommerce-cent',
		'linea-icon-ecommerce-colon',
		'linea-icon-ecommerce-creditcard',
		'linea-icon-ecommerce-diamond',
		'linea-icon-ecommerce-dollar',
		'linea-icon-ecommerce-euro',
		'linea-icon-ecommerce-franc',
		'linea-icon-ecommerce-gift',
		'linea-icon-ecommerce-graph1',
		'linea-icon-ecommerce-graph2',
		'linea-icon-ecommerce-graph3',
		'linea-icon-ecommerce-graph-decrease',
		'linea-icon-ecommerce-graph-increase',
		'linea-icon-ecommerce-guarani',
		'linea-icon-ecommerce-kips',
		'linea-icon-ecommerce-lira',
		'linea-icon-ecommerce-megaphone',
		'linea-icon-ecommerce-money',
		'linea-icon-ecommerce-naira',
		'linea-icon-ecommerce-pesos',
		'linea-icon-ecommerce-pound',
		'linea-icon-ecommerce-receipt',
		'linea-icon-ecommerce-receipt-bath',
		'linea-icon-ecommerce-receipt-cent',
		'linea-icon-ecommerce-receipt-dollar',
		'linea-icon-ecommerce-receipt-euro',
		'linea-icon-ecommerce-receipt-franc',
		'linea-icon-ecommerce-receipt-guarani',
		'linea-icon-ecommerce-receipt-kips',
		'linea-icon-ecommerce-receipt-lira',
		'linea-icon-ecommerce-receipt-naira',
		'linea-icon-ecommerce-receipt-pesos',
		'linea-icon-ecommerce-receipt-pound',
		'linea-icon-ecommerce-receipt-rublo',
		'linea-icon-ecommerce-receipt-rupee',
		'linea-icon-ecommerce-receipt-tugrik',
		'linea-icon-ecommerce-receipt-won',
		'linea-icon-ecommerce-receipt-yen',
		'linea-icon-ecommerce-receipt-yen2',
		'linea-icon-ecommerce-recept-colon',
		'linea-icon-ecommerce-rublo',
		'linea-icon-ecommerce-rupee',
		'linea-icon-ecommerce-safe',
		'linea-icon-ecommerce-sale',
		'linea-icon-ecommerce-sales',
		'linea-icon-ecommerce-ticket',
		'linea-icon-ecommerce-tugriks',
		'linea-icon-ecommerce-wallet',
		'linea-icon-ecommerce-won',
		'linea-icon-ecommerce-yen',
		'linea-icon-ecommerce-yen2',
	),
	
	'IonIcons' => array (
		'ion-ionic',
		'ion-arrow-up-a',
		'ion-arrow-right-a',
		'ion-arrow-down-a',
		'ion-arrow-left-a',
		'ion-arrow-up-b',
		'ion-arrow-right-b',
		'ion-arrow-down-b',
		'ion-arrow-left-b',
		'ion-arrow-up-c',
		'ion-arrow-right-c',
		'ion-arrow-down-c',
		'ion-arrow-left-c',
		'ion-arrow-return-right',
		'ion-arrow-return-left',
		'ion-arrow-swap',
		'ion-arrow-shrink',
		'ion-arrow-expand',
		'ion-arrow-move',
		'ion-arrow-resize',
		'ion-chevron-up',
		'ion-chevron-right',
		'ion-chevron-down',
		'ion-chevron-left',
		'ion-navicon-round',
		'ion-navicon',
		'ion-drag',
		'ion-log-in',
		'ion-log-out',
		'ion-checkmark-round',
		'ion-checkmark',
		'ion-checkmark-circled',
		'ion-close-round',
		'ion-close',
		'ion-close-circled',
		'ion-plus-round',
		'ion-plus',
		'ion-plus-circled',
		'ion-minus-round',
		'ion-minus',
		'ion-minus-circled',
		'ion-information',
		'ion-information-circled',
		'ion-help',
		'ion-help-circled',
		'ion-backspace-outline',
		'ion-backspace',
		'ion-help-buoy',
		'ion-asterisk',
		'ion-alert',
		'ion-alert-circled',
		'ion-refresh',
		'ion-loop',
		'ion-shuffle',
		'ion-home',
		'ion-search',
		'ion-flag',
		'ion-star',
		'ion-heart',
		'ion-heart-broken',
		'ion-gear-a',
		'ion-gear-b',
		'ion-toggle-filled',
		'ion-toggle',
		'ion-settings',
		'ion-wrench',
		'ion-hammer',
		'ion-edit',
		'ion-trash-a',
		'ion-trash-b',
		'ion-document',
		'ion-document-text',
		'ion-clipboard',
		'ion-scissors',
		'ion-funnel',
		'ion-bookmark',
		'ion-email',
		'ion-email-unread',
		'ion-folder',
		'ion-filing',
		'ion-archive',
		'ion-reply',
		'ion-reply-all',
		'ion-forward',
		'ion-share',
		'ion-paper-airplane',
		'ion-link',
		'ion-paperclip',
		'ion-compose',
		'ion-briefcase',
		'ion-medkit',
		'ion-at',
		'ion-pound',
		'ion-quote',
		'ion-cloud',
		'ion-upload',
		'ion-more',
		'ion-grid',
		'ion-calendar',
		'ion-clock',
		'ion-compass',
		'ion-pinpoint',
		'ion-pin',
		'ion-navigate',
		'ion-location',
		'ion-map',
		'ion-lock-combination',
		'ion-locked',
		'ion-unlocked',
		'ion-key',
		'ion-arrow-graph-up-right',
		'ion-arrow-graph-down-right',
		'ion-arrow-graph-up-left',
		'ion-arrow-graph-down-left',
		'ion-stats-bars',
		'ion-connection-bars',
		'ion-pie-graph',
		'ion-chatbubble',
		'ion-chatbubble-working',
		'ion-chatbubbles',
		'ion-chatbox',
		'ion-chatbox-working',
		'ion-chatboxes',
		'ion-person',
		'ion-person-add',
		'ion-person-stalker',
		'ion-woman',
		'ion-man',
		'ion-female',
		'ion-male',
		'ion-transgender',
		'ion-fork',
		'ion-knife',
		'ion-spoon',
		'ion-soup-can-outline',
		'ion-soup-can',
		'ion-beer',
		'ion-wineglass',
		'ion-coffee',
		'ion-icecream',
		'ion-pizza',
		'ion-power',
		'ion-mouse',
		'ion-battery-full',
		'ion-battery-half',
		'ion-battery-low',
		'ion-battery-empty',
		'ion-battery-charging',
		'ion-wifi',
		'ion-bluetooth',
		'ion-calculator',
		'ion-camera',
		'ion-eye',
		'ion-eye-disabled',
		'ion-flash',
		'ion-flash-off',
		'ion-qr-scanner',
		'ion-image',
		'ion-images',
		'ion-wand',
		'ion-contrast',
		'ion-aperture',
		'ion-crop',
		'ion-easel',
		'ion-paintbrush',
		'ion-paintbucket',
		'ion-monitor',
		'ion-laptop',
		'ion-ipad',
		'ion-iphone',
		'ion-ipod',
		'ion-printer',
		'ion-usb',
		'ion-outlet',
		'ion-bug',
		'ion-code',
		'ion-code-working',
		'ion-code-download',
		'ion-fork-repo',
		'ion-network',
		'ion-pull-request',
		'ion-merge',
		'ion-xbox',
		'ion-playstation',
		'ion-steam',
		'ion-closed-captioning',
		'ion-videocamera',
		'ion-film-marker',
		'ion-disc',
		'ion-headphone',
		'ion-music-note',
		'ion-radio-waves',
		'ion-speakerphone',
		'ion-mic-a',
		'ion-mic-b',
		'ion-mic-c',
		'ion-volume-high',
		'ion-volume-medium',
		'ion-volume-low',
		'ion-volume-mute',
		'ion-levels',
		'ion-play',
		'ion-pause',
		'ion-stop',
		'ion-record',
		'ion-skip-forward',
		'ion-skip-backward',
		'ion-eject',
		'ion-bag',
		'ion-card',
		'ion-cash',
		'ion-pricetag',
		'ion-pricetags',
		'ion-thumbsup',
		'ion-thumbsdown',
		'ion-happy-outline',
		'ion-happy',
		'ion-sad-outline',
		'ion-sad',
		'ion-bowtie',
		'ion-tshirt-outline',
		'ion-tshirt',
		'ion-trophy',
		'ion-podium',
		'ion-ribbon-a',
		'ion-ribbon-b',
		'ion-university',
		'ion-magnet',
		'ion-beaker',
		'ion-erlenmeyer-flask',
		'ion-egg',
		'ion-earth',
		'ion-planet',
		'ion-lightbulb',
		'ion-cube',
		'ion-leaf',
		'ion-waterdrop',
		'ion-flame',
		'ion-fireball',
		'ion-bonfire',
		'ion-umbrella',
		'ion-nuclear',
		'ion-no-smoking',
		'ion-thermometer',
		'ion-speedometer',
		'ion-model-s',
		'ion-plane',
		'ion-jet',
		'ion-load-a',
		'ion-load-b',
		'ion-load-c',
		'ion-load-d',
		'ion-ios-ionic-outline',
		'ion-ios-arrow-back',
		'ion-ios-arrow-forward',
		'ion-ios-arrow-up',
		'ion-ios-arrow-right',
		'ion-ios-arrow-down',
		'ion-ios-arrow-left',
		'ion-ios-arrow-thin-up',
		'ion-ios-arrow-thin-right',
		'ion-ios-arrow-thin-down',
		'ion-ios-arrow-thin-left',
		'ion-ios-circle-filled',
		'ion-ios-circle-outline',
		'ion-ios-checkmark-empty',
		'ion-ios-checkmark-outline',
		'ion-ios-checkmark',
		'ion-ios-plus-empty',
		'ion-ios-plus-outline',
		'ion-ios-plus',
		'ion-ios-close-empty',
		'ion-ios-close-outline',
		'ion-ios-close',
		'ion-ios-minus-empty',
		'ion-ios-minus-outline',
		'ion-ios-minus',
		'ion-ios-information-empty',
		'ion-ios-information-outline',
		'ion-ios-information',
		'ion-ios-help-empty',
		'ion-ios-help-outline',
		'ion-ios-help',
		'ion-ios-search',
		'ion-ios-search-strong',
		'ion-ios-star',
		'ion-ios-star-half',
		'ion-ios-star-outline',
		'ion-ios-heart',
		'ion-ios-heart-outline',
		'ion-ios-more',
		'ion-ios-more-outline',
		'ion-ios-home',
		'ion-ios-home-outline',
		'ion-ios-cloud',
		'ion-ios-cloud-outline',
		'ion-ios-cloud-upload',
		'ion-ios-cloud-upload-outline',
		'ion-ios-cloud-download',
		'ion-ios-cloud-download-outline',
		'ion-ios-upload',
		'ion-ios-upload-outline',
		'ion-ios-download',
		'ion-ios-download-outline',
		'ion-ios-refresh',
		'ion-ios-refresh-outline',
		'ion-ios-refresh-empty',
		'ion-ios-reload',
		'ion-ios-loop-strong',
		'ion-ios-loop',
		'ion-ios-bookmarks',
		'ion-ios-bookmarks-outline',
		'ion-ios-book',
		'ion-ios-book-outline',
		'ion-ios-flag',
		'ion-ios-flag-outline',
		'ion-ios-glasses',
		'ion-ios-glasses-outline',
		'ion-ios-browsers',
		'ion-ios-browsers-outline',
		'ion-ios-at',
		'ion-ios-at-outline',
		'ion-ios-pricetag',
		'ion-ios-pricetag-outline',
		'ion-ios-pricetags',
		'ion-ios-pricetags-outline',
		'ion-ios-cart',
		'ion-ios-cart-outline',
		'ion-ios-chatboxes',
		'ion-ios-chatboxes-outline',
		'ion-ios-chatbubble',
		'ion-ios-chatbubble-outline',
		'ion-ios-cog',
		'ion-ios-cog-outline',
		'ion-ios-gear',
		'ion-ios-gear-outline',
		'ion-ios-settings',
		'ion-ios-settings-strong',
		'ion-ios-toggle',
		'ion-ios-toggle-outline',
		'ion-ios-analytics',
		'ion-ios-analytics-outline',
		'ion-ios-pie',
		'ion-ios-pie-outline',
		'ion-ios-pulse',
		'ion-ios-pulse-strong',
		'ion-ios-filing',
		'ion-ios-filing-outline',
		'ion-ios-box',
		'ion-ios-box-outline',
		'ion-ios-compose',
		'ion-ios-compose-outline',
		'ion-ios-trash',
		'ion-ios-trash-outline',
		'ion-ios-copy',
		'ion-ios-copy-outline',
		'ion-ios-email',
		'ion-ios-email-outline',
		'ion-ios-undo',
		'ion-ios-undo-outline',
		'ion-ios-redo',
		'ion-ios-redo-outline',
		'ion-ios-paperplane',
		'ion-ios-paperplane-outline',
		'ion-ios-folder',
		'ion-ios-folder-outline',
		'ion-ios-paper',
		'ion-ios-paper-outline',
		'ion-ios-list',
		'ion-ios-list-outline',
		'ion-ios-world',
		'ion-ios-world-outline',
		'ion-ios-alarm',
		'ion-ios-alarm-outline',
		'ion-ios-speedometer',
		'ion-ios-speedometer-outline',
		'ion-ios-stopwatch',
		'ion-ios-stopwatch-outline',
		'ion-ios-timer',
		'ion-ios-timer-outline',
		'ion-ios-clock',
		'ion-ios-clock-outline',
		'ion-ios-time',
		'ion-ios-time-outline',
		'ion-ios-calendar',
		'ion-ios-calendar-outline',
		'ion-ios-photos',
		'ion-ios-photos-outline',
		'ion-ios-albums',
		'ion-ios-albums-outline',
		'ion-ios-camera',
		'ion-ios-camera-outline',
		'ion-ios-reverse-camera',
		'ion-ios-reverse-camera-outline',
		'ion-ios-eye',
		'ion-ios-eye-outline',
		'ion-ios-bolt',
		'ion-ios-bolt-outline',
		'ion-ios-color-wand',
		'ion-ios-color-wand-outline',
		'ion-ios-color-filter',
		'ion-ios-color-filter-outline',
		'ion-ios-grid-view',
		'ion-ios-grid-view-outline',
		'ion-ios-crop-strong',
		'ion-ios-crop',
		'ion-ios-barcode',
		'ion-ios-barcode-outline',
		'ion-ios-briefcase',
		'ion-ios-briefcase-outline',
		'ion-ios-medkit',
		'ion-ios-medkit-outline',
		'ion-ios-medical',
		'ion-ios-medical-outline',
		'ion-ios-infinite',
		'ion-ios-infinite-outline',
		'ion-ios-calculator',
		'ion-ios-calculator-outline',
		'ion-ios-keypad',
		'ion-ios-keypad-outline',
		'ion-ios-telephone',
		'ion-ios-telephone-outline',
		'ion-ios-drag',
		'ion-ios-location',
		'ion-ios-location-outline',
		'ion-ios-navigate',
		'ion-ios-navigate-outline',
		'ion-ios-locked',
		'ion-ios-locked-outline',
		'ion-ios-unlocked',
		'ion-ios-unlocked-outline',
		'ion-ios-monitor',
		'ion-ios-monitor-outline',
		'ion-ios-printer',
		'ion-ios-printer-outline',
		'ion-ios-game-controller-a',
		'ion-ios-game-controller-a-outline',
		'ion-ios-game-controller-b',
		'ion-ios-game-controller-b-outline',
		'ion-ios-americanfootball',
		'ion-ios-americanfootball-outline',
		'ion-ios-baseball',
		'ion-ios-baseball-outline',
		'ion-ios-basketball',
		'ion-ios-basketball-outline',
		'ion-ios-tennisball',
		'ion-ios-tennisball-outline',
		'ion-ios-football',
		'ion-ios-football-outline',
		'ion-ios-body',
		'ion-ios-body-outline',
		'ion-ios-person',
		'ion-ios-person-outline',
		'ion-ios-personadd',
		'ion-ios-personadd-outline',
		'ion-ios-people',
		'ion-ios-people-outline',
		'ion-ios-musical-notes',
		'ion-ios-musical-note',
		'ion-ios-bell',
		'ion-ios-bell-outline',
		'ion-ios-mic',
		'ion-ios-mic-outline',
		'ion-ios-mic-off',
		'ion-ios-volume-high',
		'ion-ios-volume-low',
		'ion-ios-play',
		'ion-ios-play-outline',
		'ion-ios-pause',
		'ion-ios-pause-outline',
		'ion-ios-recording',
		'ion-ios-recording-outline',
		'ion-ios-fastforward',
		'ion-ios-fastforward-outline',
		'ion-ios-rewind',
		'ion-ios-rewind-outline',
		'ion-ios-skipbackward',
		'ion-ios-skipbackward-outline',
		'ion-ios-skipforward',
		'ion-ios-skipforward-outline',
		'ion-ios-shuffle-strong',
		'ion-ios-shuffle',
		'ion-ios-videocam',
		'ion-ios-videocam-outline',
		'ion-ios-film',
		'ion-ios-film-outline',
		'ion-ios-flask',
		'ion-ios-flask-outline',
		'ion-ios-lightbulb',
		'ion-ios-lightbulb-outline',
		'ion-ios-wineglass',
		'ion-ios-wineglass-outline',
		'ion-ios-pint',
		'ion-ios-pint-outline',
		'ion-ios-nutrition',
		'ion-ios-nutrition-outline',
		'ion-ios-flower',
		'ion-ios-flower-outline',
		'ion-ios-rose',
		'ion-ios-rose-outline',
		'ion-ios-paw',
		'ion-ios-paw-outline',
		'ion-ios-flame',
		'ion-ios-flame-outline',
		'ion-ios-sunny',
		'ion-ios-sunny-outline',
		'ion-ios-partlysunny',
		'ion-ios-partlysunny-outline',
		'ion-ios-cloudy',
		'ion-ios-cloudy-outline',
		'ion-ios-rainy',
		'ion-ios-rainy-outline',
		'ion-ios-thunderstorm',
		'ion-ios-thunderstorm-outline',
		'ion-ios-snowy',
		'ion-ios-moon',
		'ion-ios-moon-outline',
		'ion-ios-cloudy-night',
		'ion-ios-cloudy-night-outline',
		'ion-android-arrow-up',
		'ion-android-arrow-forward',
		'ion-android-arrow-down',
		'ion-android-arrow-back',
		'ion-android-arrow-dropup',
		'ion-android-arrow-dropup-circle',
		'ion-android-arrow-dropright',
		'ion-android-arrow-dropright-circle',
		'ion-android-arrow-dropdown',
		'ion-android-arrow-dropdown-circle',
		'ion-android-arrow-dropleft',
		'ion-android-arrow-dropleft-circle',
		'ion-android-add',
		'ion-android-add-circle',
		'ion-android-remove',
		'ion-android-remove-circle',
		'ion-android-close',
		'ion-android-cancel',
		'ion-android-radio-button-off',
		'ion-android-radio-button-on',
		'ion-android-checkmark-circle',
		'ion-android-checkbox-outline-blank',
		'ion-android-checkbox-outline',
		'ion-android-checkbox-blank',
		'ion-android-checkbox',
		'ion-android-done',
		'ion-android-done-all',
		'ion-android-menu',
		'ion-android-more-horizontal',
		'ion-android-more-vertical',
		'ion-android-refresh',
		'ion-android-sync',
		'ion-android-wifi',
		'ion-android-call',
		'ion-android-apps',
		'ion-android-settings',
		'ion-android-options',
		'ion-android-funnel',
		'ion-android-search',
		'ion-android-home',
		'ion-android-cloud-outline',
		'ion-android-cloud',
		'ion-android-download',
		'ion-android-upload',
		'ion-android-cloud-done',
		'ion-android-cloud-circle',
		'ion-android-favorite-outline',
		'ion-android-favorite',
		'ion-android-star-outline',
		'ion-android-star-half',
		'ion-android-star',
		'ion-android-calendar',
		'ion-android-alarm-clock',
		'ion-android-time',
		'ion-android-stopwatch',
		'ion-android-watch',
		'ion-android-locate',
		'ion-android-navigate',
		'ion-android-pin',
		'ion-android-compass',
		'ion-android-map',
		'ion-android-walk',
		'ion-android-bicycle',
		'ion-android-car',
		'ion-android-bus',
		'ion-android-subway',
		'ion-android-train',
		'ion-android-boat',
		'ion-android-plane',
		'ion-android-restaurant',
		'ion-android-bar',
		'ion-android-cart',
		'ion-android-camera',
		'ion-android-image',
		'ion-android-film',
		'ion-android-color-palette',
		'ion-android-create',
		'ion-android-mail',
		'ion-android-drafts',
		'ion-android-send',
		'ion-android-archive',
		'ion-android-delete',
		'ion-android-attach',
		'ion-android-share',
		'ion-android-share-alt',
		'ion-android-bookmark',
		'ion-android-document',
		'ion-android-clipboard',
		'ion-android-list',
		'ion-android-folder-open',
		'ion-android-folder',
		'ion-android-print',
		'ion-android-open',
		'ion-android-exit',
		'ion-android-contract',
		'ion-android-expand',
		'ion-android-globe',
		'ion-android-chat',
		'ion-android-textsms',
		'ion-android-hangout',
		'ion-android-happy',
		'ion-android-sad',
		'ion-android-person',
		'ion-android-people',
		'ion-android-person-add',
		'ion-android-contact',
		'ion-android-contacts',
		'ion-android-playstore',
		'ion-android-lock',
		'ion-android-unlock',
		'ion-android-microphone',
		'ion-android-microphone-off',
		'ion-android-notifications-none',
		'ion-android-notifications',
		'ion-android-notifications-off',
		'ion-android-volume-mute',
		'ion-android-volume-down',
		'ion-android-volume-up',
		'ion-android-volume-off',
		'ion-android-hand',
		'ion-android-desktop',
		'ion-android-laptop',
		'ion-android-phone-portrait',
		'ion-android-phone-landscape',
		'ion-android-bulb',
		'ion-android-sunny',
		'ion-android-alert',
		'ion-android-warning',
		'ion-social-twitter',
		'ion-social-twitter-outline',
		'ion-social-facebook',
		'ion-social-facebook-outline',
		'ion-social-googleplus',
		'ion-social-googleplus-outline',
		'ion-social-google',
		'ion-social-google-outline',
		'ion-social-dribbble',
		'ion-social-dribbble-outline',
		'ion-social-octocat',
		'ion-social-github',
		'ion-social-github-outline',
		'ion-social-instagram',
		'ion-social-instagram-outline',
		'ion-social-whatsapp',
		'ion-social-whatsapp-outline',
		'ion-social-snapchat',
		'ion-social-snapchat-outline',
		'ion-social-foursquare',
		'ion-social-foursquare-outline',
		'ion-social-pinterest',
		'ion-social-pinterest-outline',
		'ion-social-rss',
		'ion-social-rss-outline',
		'ion-social-tumblr',
		'ion-social-tumblr-outline',
		'ion-social-wordpress',
		'ion-social-wordpress-outline',
		'ion-social-reddit',
		'ion-social-reddit-outline',
		'ion-social-hackernews',
		'ion-social-hackernews-outline',
		'ion-social-designernews',
		'ion-social-designernews-outline',
		'ion-social-yahoo',
		'ion-social-yahoo-outline',
		'ion-social-buffer',
		'ion-social-buffer-outline',
		'ion-social-skype',
		'ion-social-skype-outline',
		'ion-social-linkedin',
		'ion-social-linkedin-outline',
		'ion-social-vimeo',
		'ion-social-vimeo-outline',
		'ion-social-twitch',
		'ion-social-twitch-outline',
		'ion-social-youtube',
		'ion-social-youtube-outline',
		'ion-social-dropbox',
		'ion-social-dropbox-outline',
		'ion-social-apple',
		'ion-social-apple-outline',
		'ion-social-android',
		'ion-social-android-outline',
		'ion-social-windows',
		'ion-social-windows-outline',
		'ion-social-html5',
		'ion-social-html5-outline',
		'ion-social-css3',
		'ion-social-css3-outline',
		'ion-social-javascript',
		'ion-social-javascript-outline',
		'ion-social-angular',
		'ion-social-angular-outline',
		'ion-social-nodejs',
		'ion-social-sass',
		'ion-social-python',
		'ion-social-chrome',
		'ion-social-chrome-outline',
		'ion-social-codepen',
		'ion-social-codepen-outline',
		'ion-social-markdown',
		'ion-social-tux',
		'ion-social-freebsd-devil',
		'ion-social-usd',
		'ion-social-usd-outline',
		'ion-social-bitcoin',
		'ion-social-bitcoin-outline',
		'ion-social-yen',
		'ion-social-yen-outline',
		'ion-social-euro',
		'ion-social-euro-outline'
		),
);

$luv_svg_iconset = array(
	'SVGLineaIcons' => array (
			'luv-svg-icon linea-icon-basic-accelerator',
			'luv-svg-icon linea-icon-basic-alarm',
			'luv-svg-icon linea-icon-basic-anchor',
			'luv-svg-icon linea-icon-basic-anticlockwise',
			'luv-svg-icon linea-icon-basic-archive',
			'luv-svg-icon linea-icon-basic-archive-full',
			'luv-svg-icon linea-icon-basic-ban',
			'luv-svg-icon linea-icon-basic-battery-charge',
			'luv-svg-icon linea-icon-basic-battery-empty',
			'luv-svg-icon linea-icon-basic-battery-full',
			'luv-svg-icon linea-icon-basic-battery-half',
			'luv-svg-icon linea-icon-basic-bolt',
			'luv-svg-icon linea-icon-basic-book',
			'luv-svg-icon linea-icon-basic-book-pen',
			'luv-svg-icon linea-icon-basic-book-pencil',
			'luv-svg-icon linea-icon-basic-bookmark',
			'luv-svg-icon linea-icon-basic-calculator',
			'luv-svg-icon linea-icon-basic-calendar',
			'luv-svg-icon linea-icon-basic-cards-diamonds',
			'luv-svg-icon linea-icon-basic-cards-hearts',
			'luv-svg-icon linea-icon-basic-case',
			'luv-svg-icon linea-icon-basic-chronometer',
			'luv-svg-icon linea-icon-basic-clessidre',
			'luv-svg-icon linea-icon-basic-clock',
			'luv-svg-icon linea-icon-basic-clockwise',
			'luv-svg-icon linea-icon-basic-cloud',
			'luv-svg-icon linea-icon-basic-clubs',
			'luv-svg-icon linea-icon-basic-compass',
			'luv-svg-icon linea-icon-basic-cup',
			'luv-svg-icon linea-icon-basic-diamonds',
			'luv-svg-icon linea-icon-basic-display',
			'luv-svg-icon linea-icon-basic-download',
			'luv-svg-icon linea-icon-basic-exclamation',
			'luv-svg-icon linea-icon-basic-eye',
			'luv-svg-icon linea-icon-basic-eye-closed',
			'luv-svg-icon linea-icon-basic-female',
			'luv-svg-icon linea-icon-basic-flag1',
			'luv-svg-icon linea-icon-basic-flag2',
			'luv-svg-icon linea-icon-basic-floppydisk',
			'luv-svg-icon linea-icon-basic-folder',
			'luv-svg-icon linea-icon-basic-folder-multiple',
			'luv-svg-icon linea-icon-basic-gear',
			'luv-svg-icon linea-icon-basic-geolocalize-01',
			'luv-svg-icon linea-icon-basic-geolocalize-05',
			'luv-svg-icon linea-icon-basic-globe',
			'luv-svg-icon linea-icon-basic-gunsight',
			'luv-svg-icon linea-icon-basic-hammer',
			'luv-svg-icon linea-icon-basic-headset',
			'luv-svg-icon linea-icon-basic-heart',
			'luv-svg-icon linea-icon-basic-heart-broken',
			'luv-svg-icon linea-icon-basic-helm',
			'luv-svg-icon linea-icon-basic-home',
			'luv-svg-icon linea-icon-basic-info',
			'luv-svg-icon linea-icon-basic-ipod',
			'luv-svg-icon linea-icon-basic-joypad',
			'luv-svg-icon linea-icon-basic-key',
			'luv-svg-icon linea-icon-basic-keyboard',
			'luv-svg-icon linea-icon-basic-laptop',
			'luv-svg-icon linea-icon-basic-life-buoy',
			'luv-svg-icon linea-icon-basic-lightbulb',
			'luv-svg-icon linea-icon-basic-link',
			'luv-svg-icon linea-icon-basic-lock',
			'luv-svg-icon linea-icon-basic-lock-open',
			'luv-svg-icon linea-icon-basic-magic-mouse',
			'luv-svg-icon linea-icon-basic-magnifier',
			'luv-svg-icon linea-icon-basic-magnifier-minus',
			'luv-svg-icon linea-icon-basic-magnifier-plus',
			'luv-svg-icon linea-icon-basic-mail',
			'luv-svg-icon linea-icon-basic-mail-multiple',
			'luv-svg-icon linea-icon-basic-mail-open',
			'luv-svg-icon linea-icon-basic-mail-open-text',
			'luv-svg-icon linea-icon-basic-male',
			'luv-svg-icon linea-icon-basic-map',
			'luv-svg-icon linea-icon-basic-message',
			'luv-svg-icon linea-icon-basic-message-multiple',
			'luv-svg-icon linea-icon-basic-message-txt',
			'luv-svg-icon linea-icon-basic-mixer2',
			'luv-svg-icon linea-icon-basic-mouse',
			'luv-svg-icon linea-icon-basic-notebook',
			'luv-svg-icon linea-icon-basic-notebook-pen',
			'luv-svg-icon linea-icon-basic-notebook-pencil',
			'luv-svg-icon linea-icon-basic-paperplane',
			'luv-svg-icon linea-icon-basic-pencil-ruler',
			'luv-svg-icon linea-icon-basic-pencil-ruler-pen',
			'luv-svg-icon linea-icon-basic-photo',
			'luv-svg-icon linea-icon-basic-picture',
			'luv-svg-icon linea-icon-basic-picture-multiple',
			'luv-svg-icon linea-icon-basic-pin1',
			'luv-svg-icon linea-icon-basic-pin2',
			'luv-svg-icon linea-icon-basic-postcard',
			'luv-svg-icon linea-icon-basic-postcard-multiple',
			'luv-svg-icon linea-icon-basic-printer',
			'luv-svg-icon linea-icon-basic-question',
			'luv-svg-icon linea-icon-basic-rss',
			'luv-svg-icon linea-icon-basic-server',
			'luv-svg-icon linea-icon-basic-server2',
			'luv-svg-icon linea-icon-basic-server-cloud',
			'luv-svg-icon linea-icon-basic-server-download',
			'luv-svg-icon linea-icon-basic-server-upload',
			'luv-svg-icon linea-icon-basic-settings',
			'luv-svg-icon linea-icon-basic-share',
			'luv-svg-icon linea-icon-basic-sheet',
			'luv-svg-icon linea-icon-basic-sheet-multiple',
			'luv-svg-icon linea-icon-basic-sheet-pen',
			'luv-svg-icon linea-icon-basic-sheet-pencil',
			'luv-svg-icon linea-icon-basic-sheet-txt',
			'luv-svg-icon linea-icon-basic-signs',
			'luv-svg-icon linea-icon-basic-smartphone',
			'luv-svg-icon linea-icon-basic-spades',
			'luv-svg-icon linea-icon-basic-spread',
			'luv-svg-icon linea-icon-basic-spread-bookmark',
			'luv-svg-icon linea-icon-basic-spread-text',
			'luv-svg-icon linea-icon-basic-spread-text-bookmark',
			'luv-svg-icon linea-icon-basic-star',
			'luv-svg-icon linea-icon-basic-tablet',
			'luv-svg-icon linea-icon-basic-target',
			'luv-svg-icon linea-icon-basic-todo',
			'luv-svg-icon linea-icon-basic-todo-pen',
			'luv-svg-icon linea-icon-basic-todo-pencil',
			'luv-svg-icon linea-icon-basic-todo-txt',
			'luv-svg-icon linea-icon-basic-todolist-pen',
			'luv-svg-icon linea-icon-basic-todolist-pencil',
			'luv-svg-icon linea-icon-basic-trashcan',
			'luv-svg-icon linea-icon-basic-trashcan-full',
			'luv-svg-icon linea-icon-basic-trashcan-refresh',
			'luv-svg-icon linea-icon-basic-trashcan-remove',
			'luv-svg-icon linea-icon-basic-upload',
			'luv-svg-icon linea-icon-basic-usb',
			'luv-svg-icon linea-icon-basic-video',
			'luv-svg-icon linea-icon-basic-watch',
			'luv-svg-icon linea-icon-basic-webpage',
			'luv-svg-icon linea-icon-basic-webpage-img-txt',
			'luv-svg-icon linea-icon-basic-webpage-multiple',
			'luv-svg-icon linea-icon-basic-webpage-txt',
			'luv-svg-icon linea-icon-basic-world',
			'luv-svg-icon linea-icon-ecommerce-bag',
			'luv-svg-icon linea-icon-ecommerce-bag-check',
			'luv-svg-icon linea-icon-ecommerce-bag-cloud',
			'luv-svg-icon linea-icon-ecommerce-bag-download',
			'luv-svg-icon linea-icon-ecommerce-bag-minus',
			'luv-svg-icon linea-icon-ecommerce-bag-plus',
			'luv-svg-icon linea-icon-ecommerce-bag-refresh',
			'luv-svg-icon linea-icon-ecommerce-bag-remove',
			'luv-svg-icon linea-icon-ecommerce-bag-search',
			'luv-svg-icon linea-icon-ecommerce-bag-upload',
			'luv-svg-icon linea-icon-ecommerce-banknote',
			'luv-svg-icon linea-icon-ecommerce-banknotes',
			'luv-svg-icon linea-icon-ecommerce-basket',
			'luv-svg-icon linea-icon-ecommerce-basket-check',
			'luv-svg-icon linea-icon-ecommerce-basket-cloud',
			'luv-svg-icon linea-icon-ecommerce-basket-download',
			'luv-svg-icon linea-icon-ecommerce-basket-minus',
			'luv-svg-icon linea-icon-ecommerce-basket-plus',
			'luv-svg-icon linea-icon-ecommerce-basket-refresh',
			'luv-svg-icon linea-icon-ecommerce-basket-remove',
			'luv-svg-icon linea-icon-ecommerce-basket-search',
			'luv-svg-icon linea-icon-ecommerce-basket-upload',
			'luv-svg-icon linea-icon-ecommerce-bath',
			'luv-svg-icon linea-icon-ecommerce-cart',
			'luv-svg-icon linea-icon-ecommerce-cart-check',
			'luv-svg-icon linea-icon-ecommerce-cart-cloud',
			'luv-svg-icon linea-icon-ecommerce-cart-content',
			'luv-svg-icon linea-icon-ecommerce-cart-download',
			'luv-svg-icon linea-icon-ecommerce-cart-minus',
			'luv-svg-icon linea-icon-ecommerce-cart-plus',
			'luv-svg-icon linea-icon-ecommerce-cart-refresh',
			'luv-svg-icon linea-icon-ecommerce-cart-remove',
			'luv-svg-icon linea-icon-ecommerce-cart-search',
			'luv-svg-icon linea-icon-ecommerce-cart-upload',
			'luv-svg-icon linea-icon-ecommerce-cent',
			'luv-svg-icon linea-icon-ecommerce-colon',
			'luv-svg-icon linea-icon-ecommerce-creditcard',
			'luv-svg-icon linea-icon-ecommerce-diamond',
			'luv-svg-icon linea-icon-ecommerce-dollar',
			'luv-svg-icon linea-icon-ecommerce-euro',
			'luv-svg-icon linea-icon-ecommerce-franc',
			'luv-svg-icon linea-icon-ecommerce-gift',
			'luv-svg-icon linea-icon-ecommerce-graph1',
			'luv-svg-icon linea-icon-ecommerce-graph2',
			'luv-svg-icon linea-icon-ecommerce-graph3',
			'luv-svg-icon linea-icon-ecommerce-graph-decrease',
			'luv-svg-icon linea-icon-ecommerce-graph-increase',
			'luv-svg-icon linea-icon-ecommerce-guarani',
			'luv-svg-icon linea-icon-ecommerce-kips',
			'luv-svg-icon linea-icon-ecommerce-lira',
			'luv-svg-icon linea-icon-ecommerce-megaphone',
			'luv-svg-icon linea-icon-ecommerce-money',
			'luv-svg-icon linea-icon-ecommerce-naira',
			'luv-svg-icon linea-icon-ecommerce-pesos',
			'luv-svg-icon linea-icon-ecommerce-pound',
			'luv-svg-icon linea-icon-ecommerce-receipt',
			'luv-svg-icon linea-icon-ecommerce-receipt-bath',
			'luv-svg-icon linea-icon-ecommerce-receipt-cent',
			'luv-svg-icon linea-icon-ecommerce-receipt-dollar',
			'luv-svg-icon linea-icon-ecommerce-receipt-euro',
			'luv-svg-icon linea-icon-ecommerce-receipt-franc',
			'luv-svg-icon linea-icon-ecommerce-receipt-guarani',
			'luv-svg-icon linea-icon-ecommerce-receipt-kips',
			'luv-svg-icon linea-icon-ecommerce-receipt-lira',
			'luv-svg-icon linea-icon-ecommerce-receipt-naira',
			'luv-svg-icon linea-icon-ecommerce-receipt-pesos',
			'luv-svg-icon linea-icon-ecommerce-receipt-pound',
			'luv-svg-icon linea-icon-ecommerce-receipt-rublo',
			'luv-svg-icon linea-icon-ecommerce-receipt-rupee',
			'luv-svg-icon linea-icon-ecommerce-receipt-tugrik',
			'luv-svg-icon linea-icon-ecommerce-receipt-won',
			'luv-svg-icon linea-icon-ecommerce-receipt-yen',
			'luv-svg-icon linea-icon-ecommerce-receipt-yen2',
			'luv-svg-icon linea-icon-ecommerce-recept-colon',
			'luv-svg-icon linea-icon-ecommerce-rublo',
			'luv-svg-icon linea-icon-ecommerce-rupee',
			'luv-svg-icon linea-icon-ecommerce-safe',
			'luv-svg-icon linea-icon-ecommerce-sale',
			'luv-svg-icon linea-icon-ecommerce-sales',
			'luv-svg-icon linea-icon-ecommerce-ticket',
			'luv-svg-icon linea-icon-ecommerce-tugriks',
			'luv-svg-icon linea-icon-ecommerce-wallet',
			'luv-svg-icon linea-icon-ecommerce-won',
			'luv-svg-icon linea-icon-ecommerce-yen',
			'luv-svg-icon linea-icon-ecommerce-yen2',
			'luv-svg-icon linea-icon-music-beginning-button',
			'luv-svg-icon linea-icon-music-bell',
			'luv-svg-icon linea-icon-music-cd',
			'luv-svg-icon linea-icon-music-diapason',
			'luv-svg-icon linea-icon-music-eject-button',
			'luv-svg-icon linea-icon-music-end-button',
			'luv-svg-icon linea-icon-music-fastforward-button',
			'luv-svg-icon linea-icon-music-headphones',
			'luv-svg-icon linea-icon-music-ipod',
			'luv-svg-icon linea-icon-music-loudspeaker',
			'luv-svg-icon linea-icon-music-microphone',
			'luv-svg-icon linea-icon-music-microphone-old',
			'luv-svg-icon linea-icon-music-mixer',
			'luv-svg-icon linea-icon-music-mute',
			'luv-svg-icon linea-icon-music-note-multiple',
			'luv-svg-icon linea-icon-music-note-single',
			'luv-svg-icon linea-icon-music-pause-button',
			'luv-svg-icon linea-icon-music-play-button',
			'luv-svg-icon linea-icon-music-playlist',
			'luv-svg-icon linea-icon-music-radio-ghettoblaster',
			'luv-svg-icon linea-icon-music-radio-portable',
			'luv-svg-icon linea-icon-music-record',
			'luv-svg-icon linea-icon-music-recordplayer',
			'luv-svg-icon linea-icon-music-repeat-button',
			'luv-svg-icon linea-icon-music-rewind-button',
			'luv-svg-icon linea-icon-music-shuffle-button',
			'luv-svg-icon linea-icon-music-stop-button',
			'luv-svg-icon linea-icon-music-tape',
			'luv-svg-icon linea-icon-music-volume-down',
			'luv-svg-icon linea-icon-music-volume-up',
			'luv-svg-icon linea-icon-ecommerce-bag',
			'luv-svg-icon linea-icon-ecommerce-bag-check',
			'luv-svg-icon linea-icon-ecommerce-bag-cloud',
			'luv-svg-icon linea-icon-ecommerce-bag-download',
			'luv-svg-icon linea-icon-ecommerce-bag-minus',
			'luv-svg-icon linea-icon-ecommerce-bag-plus',
			'luv-svg-icon linea-icon-ecommerce-bag-refresh',
			'luv-svg-icon linea-icon-ecommerce-bag-remove',
			'luv-svg-icon linea-icon-ecommerce-bag-search',
			'luv-svg-icon linea-icon-ecommerce-bag-upload',
			'luv-svg-icon linea-icon-ecommerce-banknote',
			'luv-svg-icon linea-icon-ecommerce-banknotes',
			'luv-svg-icon linea-icon-ecommerce-basket',
			'luv-svg-icon linea-icon-ecommerce-basket-check',
			'luv-svg-icon linea-icon-ecommerce-basket-cloud',
			'luv-svg-icon linea-icon-ecommerce-basket-download',
			'luv-svg-icon linea-icon-ecommerce-basket-minus',
			'luv-svg-icon linea-icon-ecommerce-basket-plus',
			'luv-svg-icon linea-icon-ecommerce-basket-refresh',
			'luv-svg-icon linea-icon-ecommerce-basket-remove',
			'luv-svg-icon linea-icon-ecommerce-basket-search',
			'luv-svg-icon linea-icon-ecommerce-basket-upload',
			'luv-svg-icon linea-icon-ecommerce-bath',
			'luv-svg-icon linea-icon-ecommerce-cart',
			'luv-svg-icon linea-icon-ecommerce-cart-check',
			'luv-svg-icon linea-icon-ecommerce-cart-cloud',
			'luv-svg-icon linea-icon-ecommerce-cart-content',
			'luv-svg-icon linea-icon-ecommerce-cart-download',
			'luv-svg-icon linea-icon-ecommerce-cart-minus',
			'luv-svg-icon linea-icon-ecommerce-cart-plus',
			'luv-svg-icon linea-icon-ecommerce-cart-refresh',
			'luv-svg-icon linea-icon-ecommerce-cart-remove',
			'luv-svg-icon linea-icon-ecommerce-cart-search',
			'luv-svg-icon linea-icon-ecommerce-cart-upload',
			'luv-svg-icon linea-icon-ecommerce-cent',
			'luv-svg-icon linea-icon-ecommerce-colon',
			'luv-svg-icon linea-icon-ecommerce-creditcard',
			'luv-svg-icon linea-icon-ecommerce-diamond',
			'luv-svg-icon linea-icon-ecommerce-dollar',
			'luv-svg-icon linea-icon-ecommerce-euro',
			'luv-svg-icon linea-icon-ecommerce-franc',
			'luv-svg-icon linea-icon-ecommerce-gift',
			'luv-svg-icon linea-icon-ecommerce-graph1',
			'luv-svg-icon linea-icon-ecommerce-graph2',
			'luv-svg-icon linea-icon-ecommerce-graph3',
			'luv-svg-icon linea-icon-ecommerce-graph-decrease',
			'luv-svg-icon linea-icon-ecommerce-graph-increase',
			'luv-svg-icon linea-icon-ecommerce-guarani',
			'luv-svg-icon linea-icon-ecommerce-kips',
			'luv-svg-icon linea-icon-ecommerce-lira',
			'luv-svg-icon linea-icon-ecommerce-megaphone',
			'luv-svg-icon linea-icon-ecommerce-money',
			'luv-svg-icon linea-icon-ecommerce-naira',
			'luv-svg-icon linea-icon-ecommerce-pesos',
			'luv-svg-icon linea-icon-ecommerce-pound',
			'luv-svg-icon linea-icon-ecommerce-receipt',
			'luv-svg-icon linea-icon-ecommerce-receipt-bath',
			'luv-svg-icon linea-icon-ecommerce-receipt-cent',
			'luv-svg-icon linea-icon-ecommerce-receipt-dollar',
			'luv-svg-icon linea-icon-ecommerce-receipt-euro',
			'luv-svg-icon linea-icon-ecommerce-receipt-franc',
			'luv-svg-icon linea-icon-ecommerce-receipt-guarani',
			'luv-svg-icon linea-icon-ecommerce-receipt-kips',
			'luv-svg-icon linea-icon-ecommerce-receipt-lira',
			'luv-svg-icon linea-icon-ecommerce-receipt-naira',
			'luv-svg-icon linea-icon-ecommerce-receipt-pesos',
			'luv-svg-icon linea-icon-ecommerce-receipt-pound',
			'luv-svg-icon linea-icon-ecommerce-receipt-rublo',
			'luv-svg-icon linea-icon-ecommerce-receipt-rupee',
			'luv-svg-icon linea-icon-ecommerce-receipt-tugrik',
			'luv-svg-icon linea-icon-ecommerce-receipt-won',
			'luv-svg-icon linea-icon-ecommerce-receipt-yen',
			'luv-svg-icon linea-icon-ecommerce-receipt-yen2',
			'luv-svg-icon linea-icon-ecommerce-recept-colon',
			'luv-svg-icon linea-icon-ecommerce-rublo',
			'luv-svg-icon linea-icon-ecommerce-rupee',
			'luv-svg-icon linea-icon-ecommerce-safe',
			'luv-svg-icon linea-icon-ecommerce-sale',
			'luv-svg-icon linea-icon-ecommerce-sales',
			'luv-svg-icon linea-icon-ecommerce-ticket',
			'luv-svg-icon linea-icon-ecommerce-tugriks',
			'luv-svg-icon linea-icon-ecommerce-wallet',
			'luv-svg-icon linea-icon-ecommerce-won',
			'luv-svg-icon linea-icon-ecommerce-yen',
			'luv-svg-icon linea-icon-ecommerce-yen2',
	),
)

?>